"vim config file
filetype off

" not compatible with vi 
set nocompatible

" vundle plugin
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Plugin 'gmarik/vundle'
" plugins to load
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'kien/ctrlp.vim'
Plugin 'git://git.code.sf.net/p/vim-latex/vim-latex'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-notes'
" show mode your in
set showmode

" persistent undo
set undofile
set undodir=$HOME/.local/share/undo

" set hidden file
set hidden

"tabing
set smarttab 
set tabstop=8
set shiftwidth=4
set softtabstop=4
set modeline
set expandtab
set autoindent
set smartindent

"python
filetype on
filetype plugin on
syntax on
filetype indent on
filetype indent plugin on
set ofu=syntaxcomplete#Complete "omni compete
syntax enable
set foldmethod=indent
set foldlevel=99

" add $ at end point of change
set cpoptions+=$

" not adding comment sign on next line after comment
autocmd FileType * setlocal formatoptions-=r formatoptions-=o

" linenumbering
set nu
set relativenumber

" search
set incsearch " start search as you type
set hlsearch
set ignorecase
" pressing \ space makes no search highlight
nmap <silent> <leader><space> :nohlsearch<CR>

" make h,j,k,l move between visual lines
nnoremap j gj
nnoremap k gk

" file explorer
map <leader>e :Ex<CR>

" make useful status line
set laststatus=2
set statusline+=%F\ %=%y\ %P 
set showcmd " show key pressed in normal mode

" color
set t_Co=256

colorscheme wombat256
set background=dark

" tab completion
set wildmenu
set wildignore=*.pyc,*.aux,*.lot,*.out,*.lof,*.log,*.toc " ignore latex produced files

" path to search through
set path+=**

" no swap or backup files
set noswapfile
set nobackup
set nowb

" tex type latex
let g:tex_flavor='latex'
let g:Tex_DefaultTargetFormat='pdf'
let g:Tex_SmartKeyQuote=0
set shellslash
set grepprg=grep\ -nH\ $*
